DROP TABLE BOARDLIST;

create table boardList(
    BID number,
    BTITLE VARCHAR2(20) CONSTRAINT NN_BTITLE NOT NULL,
    BWRITER VARCHAR2(12) CONSTRAINT NN_BWRITER NOT NULL,
    BDATE VARCHAR2(20) CONSTRAINT NN_BDATE NOT NULL,
    CONTENT CLOB,
    COUNT NUMBER,
    CONSTRAINT PK_BID PRIMARY KEY (BID)
);

CREATE SEQUENCE SEQ_BID
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

commit;
